services:
# Grafana Container
  grafana:
    image: grafana/grafana:latest
    container_name: grafana_cdv
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      cdv_grafana:
      internal_network:
        ipv4_address: 192.168.10.150
# InfluxDB Container
  influxdb:
    image: influxdb:latest
    container_name: influxdb_cdv
    restart: unless-stopped
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=${INFLUXDB_DB}
      - INFLUXDB_ADMIN_USER=${INFLUXDB_ADMIN_USER}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
      - INFLUXDB_USER=${INFLUXDB_USER}
      - INFLUXDB_USER_PASSWORD=${INFLUXDB_USER_PASSWORD}
    volumes:
      - influxdb_data:/var/lib/influxdb
    networks:
      internal_network:
        ipv4_address: 192.168.10.100
  mqtt_subscriber:
    build: .
    container_name: mqtt_subscriber_cdv
    restart: unless-stopped
    volumes:
      - .:/app
    depends_on:
      - influxdb
    networks:
      internal_network:
        ipv4_address: 192.168.10.151
    environment:
      - CA_CERT_PATH=/app/emqxsl-ca.crt  # ścieżka do certyfikatu w kontenerze

secrets:
  ca_certificate:
    file: ./emqxsl-ca.crt

# Containers Volumes
volumes:
  grafana_data:
  influxdb_data:

# Containers networks 
networks:
  cdv_grafana:
    
  internal_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.10.0/24